# Generated by Django 5.2.1 on 2025-06-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTrackerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
