# Generated by Django 5.2.1 on 2025-06-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetrackermodel',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='expensetrackermodel',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=7),
        ),
        migrations.AlterField(
            model_name='expensetrackermodel',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
